apiVersion: kos-operator.stable.sap.cc/v1
kind: KosQuery
metadata:
  name: baremetal-blocks
  namespace: monsoon3
requirements:
- name: ironic-seed
  kind: OpenstackSeed
context: ironic@Default/service
python: |
  blocks = set(node.name.split('-')[-1] for node in os.baremetal.nodes())
